#!/usr/bin/env bash
#If you call command below, it will generate metrics for you. Visit http://localhost:8080/metrics to list metrics.

for ((i=1;i<=100;i++)); do curl "http://localhost:8080/api/v1/balances"; done
